common:
  appName: 'ukhouseprices'

plot_fonts:
  font:
    'family': 'serif'
    'color': 'darkred'
    'weight': 'normal'
    'size': 10

  # define font dictionary
  font_small:
    'family': 'serif'
    'color': 'darkred'
    'weight': 'normal'
    'size': 7

hiveVariables:
  DSDB: "DS"
  regionname: "Kensington and Chelsea"
  Boston_csvlocation: "hdfs://rhes75:9000/ds/Boston.csv"
  London_csvLocation: "hdfs://rhes75:9000/ds/UK-HPI-full-file-2020-01.csv"
  settings :
      ("hive.exec.dynamic.partition", "true"),
      ("hive.exec.dynamic.partition.mode", "nonstrict"),
      ("hive.stats.autogather", "true")

GCPVariables:
  projectId: 'axial-glow-224522'
  datasetLocation: "europe-west2"
  bucketname: 'etcbucket'
  sourceDataset: "staging"
  sourceTable: "ukhouseprices"
  inputTable: sourceDataset+"."+sourceTable
  fullyQualifiedInputTableId: projectId+":"+inputTable
  targetDataset: "ds"
  targetTable: "summary"
  outputTable: targetDataset+"."+targetTable
  fullyQualifiedoutputTableId: projectId+":"+outputTable
  tmp_bucket: "tmp_storage_bucket/tmp"
  jsonKeyFile: "/home/hduser/GCPFirstProject-d75f1b3a9817.json"
  DB: "DS"
  yearlyAveragePricesAllTable: "yearlyaveragepricesAllTable"
  percentYearlyHousePriceChange: "percentyearlyhousepricechange"


